library(clusterProfiler)
library(enrichplot)
# we use ggplot2 to add x axis labels (ex: ridgeplot)
library(ggplot2)

############################
data_lines <- read.table("C:/Users/ritas/Desktop/TESE_IMM/GSEA/PRIMARY_WITH_RESPONSE_ONLY_CODING_GENES/GSEA_RES.txt",sep = ",")
View(data_lines)

##################################################################

# we want the log2 fold change 
original_gene_list <- data_lines$log2FoldChange

# name the vector
names(original_gene_list) <- rownames(data_lines)

# omit any NA values 
gene_list<-na.omit(original_gene_list)

# sort the list in decreasing order (required for clusterProfiler)
gene_list = sort(gene_list, decreasing = TRUE)
View(gene_list)#18,194 genes in total/18,520 gene names
View(final_db)

library(org.Hs.eg.db)
keytypes(org.Hs.eg.db)

#########################1ºGO TERMS:#################################
gse <- gseGO(geneList=gene_list, 
             ont ="ALL", 
             keyType = "SYMBOL", 
             nPerm = 10000, 
             minGSSize = 3, 
             maxGSSize = 800, 
             pvalueCutoff = 0.05, 
             verbose = TRUE, 
             OrgDb=org.Hs.eg.db, 
             pAdjustMethod = "none",)# Benjamini-Hochberg procedure
gse
View(gse@result)
GO_TERMS_PRIMARY_RESPONSE<-as.data.frame(gse@result)
library(openxlsx)
write.xlsx(GO_TERMS_PRIMARY_RESPONSE, "C:/Users/ritas/Desktop/TESE_IMM/GSEA/PRIMARY_WITH_RESPONSE_ONLY_CODING_GENES/go_terms_primary_progressive_response.xlsx")

# Create a dot plot
dotplot(selected_results, split = ".sign") + facet_grid(.~.sign)

#Enrichment Map:Enrichment map organizes enriched terms into a network with edges connecting overlapping gene sets. In this way, mutually overlapping gene sets are tend to cluster together, making it easy to identify functional modules.
x2 <- pairwise_termsim(gse) 
emapplot(x2, showCategory = 30) + theme(text = element_text(size = 30))

#Category Netplot
cnetplot(gse,showCategory = 10,categorySize="pvalue", foldChange=gene_list,)

#Ridgeplot
#Grouped by gene set, density plots are generated by using the frequency of fold change values per gene within each set. Helpful to interpret up/down-regulated pathways.
ridgeplot(gse) + labs(x = "enrichment distribution")

#########################1ºKEGG PATHWAYS:#################################
#toType in the bitr function has to be one of the available options from keyTypes(org.Dm.eg.db) and must map to one of ‘kegg’, ‘ncbi-geneid’, ‘ncib-proteinid’ or ‘uniprot’ because gseKEGG() only accepts one of these 4 options as it’s keytype parameter. In the case of org.Dm.eg.db, none of those 4 types are available, but ‘ENTREZID’ are the same as ncbi-geneid for org.Dm.eg.db so we use this for toType.
# Convert gene IDs for gseKEGG function
# We will lose some genes here because not all IDs will be converted
ids<-bitr(names(original_gene_list), fromType = "SYMBOL", toType = "ENTREZID", OrgDb=org.Hs.eg.db)
View(ids)
# remove duplicate IDS (here I use "ENSEMBL", but it should be whatever was selected as keyType)
dedup_ids = ids[!duplicated(ids[c("SYMBOL")]),]
dedup_ids
# Create a new dataframe df2 which has only the genes which were successfully mapped using the bitr function above
df2 = data_lines[rownames(data_lines) %in% dedup_ids$SYMBOL,]
View(df2)
data_lines
# Create a new column in df2 with the corresponding ENTREZ IDs
df2$Y = dedup_ids$ENTREZID
df2$Y
# Create a vector of the gene unuiverse
kegg_gene_list <- df2$log2FoldChange
kegg_gene_list
# Name vector with ENTREZ ids
names(kegg_gene_list) <- df2$Y

# omit any NA values 
kegg_gene_list<-na.omit(kegg_gene_list)

# sort the list in decreasing order (required for clusterProfiler)
kegg_gene_list = sort(kegg_gene_list, decreasing = TRUE)
View(kegg_gene_list)#18182 genes in total

gsea_kegg <- gseKEGG(geneList     = kegg_gene_list,
                     organism     = "hsa",
                     nPerm        = 10000,
                     minGSSize    = 3,
                     maxGSSize    = 800,
                     pvalueCutoff = 0.05,
                     pAdjustMethod = "none",
                     keyType       = "ncbi-geneid")
gsea_kegg  
KEGG_PATHWAYS_PRIMARY_RESPONSE<-as.data.frame(gsea_kegg@result)
View(KEGG_PATHWAYS_PRIMARY_RESPONSE)
library(xlsx)
write.xlsx(KEGG_PATHWAYS_PRIMARY_RESPONSE, "C:/Users/ritas/Desktop/TESE_IMM/GSEA/PRIMARY_WITH_RESPONSE_ONLY_CODING_GENES/KEGG_PATHWAYS_primary_progressive_response.xlsx")


#DOTPLOT WITH KEGG PATHWAYS
dotplot(gsea_kegg, showCategory = 15,font.size = 18, split=".sign") + facet_grid(.~.sign)

#Encrichment map
KEGG_enr_map <- pairwise_termsim(gsea_kegg) 
emapplot(KEGG_enr_map,showCategory = 40)

#Category Netplot
cnetplot(gsea_kegg, categorySize="pvalue", foldChange=kegg_gene_list,showCategory = 10)

#Ridgeplot
ridgeplot(gsea_kegg) + labs(x = "enrichment distribution")

